spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account_book?serverTimezone=UTC&characterEncoding=UTF-8
    username: sanghyunlee
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#create
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace